
[proxy]
socks_listen = 9150

[logging]
console = "info"
log_sensitive_information = true

files = [
 {path = "info.log", filter="info", rotate="daily"},
# {path = "debug.log", filter="debug", rotate="daily"},
# {path = "trace.log", filter="trace", rotate="daily"},
]

[address_filter]
allow_onion_addrs = true

[storage]
state_dir = "./"
cache_dir = "./cache"

[storage.keystore]
enabled = "auto"
